Chroot на практике

* Chroot на практике
  :PROPERTIES:
  :CUSTOM_ID: chroot-на-практике
  :END:

unix-lab.org [[https://www.unix-lab.org/posts/chroot/]]

** 3-4 минуты
   :PROPERTIES:
   :CUSTOM_ID: минуты
   :END:

Изменение корня это процесс изменения видимой на диске корневой
директории (и текущего запуска процессов) на другую корневую директорию.
Когда вы изменили корневую директорию на другую, вы больше не имеете
доступа к файлам и командам за пределами этой директории. Эта директория
становится подобна заключению пользователя в клетку. Изменение корневой
директории обычно нужно для таких задач как переустановка GRUB или сброс
забытого пароля и чаще осуществляется при помощи LiveCD или LiveUSB в
монтируемый раздел, содержащий установленную систему.

Вы должны загрузиться с любой работающей среды Linux (например, с LiveCD
или USB flash disk). Для работы с chroot потребуются привилегии
суперпользователя.

Убедитесь, что архитектура среды Linux, с которой вы загрузились
соответствует архитектуре системы, с которой вы будете работать (т.e.
i686, x86_64). Вы можете просмотреть архитектуру среды командой: |uname
-m|

- Монтирование каталогов

Чтобы просмотреть все имеющиеся дисковые разделы и их типы введите:
=lsblk=

Создайте директорию, куда вы хотели бы подмонтировать устройство или
раздел:

#+BEGIN_EXAMPLE
  # mkdir /mnt/arch
  # mount /dev/sda3 /mnt/arch
#+END_EXAMPLE

- Изменение корневой директории

Подмонтируйте временные файловые системы:

#+BEGIN_EXAMPLE
  # mount -t proc none /mnt/arch/proc
  # mount -t sysfs sys /mnt/arch/sys
  # mount -o bind /dev /mnt/arch/dev
#+END_EXAMPLE

- Монтируйте другие разделы, если нуждаетесь в них (такие как |/boot,
  /var, /usr|). Например:

#+BEGIN_EXAMPLE
  # mount /dev/sda1 /mnt/arch/boot
#+END_EXAMPLE

После выхода из изолированной среды, вы сможете отмонтировать все
разделы одной командой. Это позволит безопасно отключить систему.

Если при нахождении в среде chroot вам нужна будет работа в сети,
скопируйте информацию о DNS в новый корневой каталог:

#+BEGIN_EXAMPLE
  # cp -L /etc/resolv.conf etc/resolv.conf
#+END_EXAMPLE

- Переходим в новую среду:

#+BEGIN_EXAMPLE
  # chroot /mnt/arch /bin/bash
#+END_EXAMPLE

Если вы увидите ошибку
="chroot: cannot run command '/bin/bash': Exec format error"= это может
означать, что архитектуры не совпадают.

При работе с GRUB в изолированной среде нужно быть уверенным, что
каталог =/etc/mtab= содержит актуальную информацию:

#+BEGIN_EXAMPLE
  # grep -v rootfs /proc/mounts > /etc/mtab
#+END_EXAMPLE

- Следующие шаги:

#+BEGIN_EXAMPLE
  # source /etc/profile
  # export PS1="(chroot) $PS1"
#+END_EXAMPLE

- Обслуживание системы:

< Вот то, что вы можете сделать в изолированной среде: >

#+BEGIN_EXAMPLE
    1. Обновить или откатить пакеты
    2. Пересобрать образ initcpio
    3. Сбросить забытый пароль
    4. Исправить /etc/fstab
    5. Переустановить GRUB
#+END_EXAMPLE

- Выход из chroot окружения:

Когда вы закончите работу, выйдите из chroot, введя команду =exit=.

Теперь отмонтируйте устройства и каталоги, которые вам больше не нужны:

#+BEGIN_EXAMPLE
  # umount {proc,sys,dev,boot...}
#+END_EXAMPLE

Наконец отмонтируйте ваш жёсткий диск:

#+BEGIN_EXAMPLE
  # cd /
  # umount /mnt/arch
#+END_EXAMPLE

Если вы видите ошибку подобную этой:
="/mnt (или другой каталог) is busy"=, вы можете узнать причину
(используя |lsof|) или принудительно отмонтировать каталог:

После этого вы сможете безопасно отключить систему. ⤧
