* Optimus Manager в Arch Linux

# Optimus Manager в Arch Linux и Manjaro Linux

 [![Аватар](:/d0b2fd3ac5704a05bf2a1831ec821902)](https://archblog.pro/?author=1) Опубликовано [Stez](https://archblog.pro/?author=1 "Записи Stez") [24/09/2019](https://archblog.pro/?m=201909) в [Arch Linux](https://archblog.pro/?cat=4 "View all posts in Arch Linux") 5.4K

Рассмотрим установку **Optimus Manager** для переключение графики Intel+Nvidia

На данный момент программа поддерживает следующие дисплейные менеджеры : **SDDM, LightDM, GDM(инфа ниже)**

**Обновление v1.2 — 21.09.2019**: Добавлен новый режим переключения **hybrid**  
В данном режиме загружны оба модуля видеокарт, работа данного режима описана в статье про [PRIME Render Offload в Arch и Manjaro Linux](https://archblog.pro/?p=566). Для данного режима так же требуются **435** драйвер и патченый **xorg-server**

**Если после перезагрузки вы видите черный экран:**

Для некоторых моделей ноутбука требуется добавить в настройка Grub параметр ядра**:**

`acpi_osi=! acpi_osi="Windows 2009"`

Если вы используете **Gnome или Gnome Display Manager (GDM)**, существует несколько дополнительных требований для использования **optimus-manager**:

Пакет по умолчанию `gdm` из репозиториев Archlinux и Manjaro **не совместим с optimus-manager**, поэтому вы должны заменить его на эту исправленную версию: **[gdm-prime](https://aur.archlinux.org/packages/gdm-prime/)** (также заменяет `libgdm`).

Gnome по умолчанию запускает сеансы **Wayland**, который несовместим с **optimus-manager**.

**Manjaro KDE** : **Manjaro** поставляется с конфигурацией по умолчанию для SDDM (менеджер входа в систему по умолчанию для **KDE**), которая переопределяет некоторые ключи, необходимые для **optimus-manager.** Чтобы это исправить, вам нужно отредактировать файл `/etc/sddm.conf`и просто поставить `#`перед строками: `DisplayCommand` и `DisplayStopCommand`.

Если вы используете **Bumblebee** то рекомендую от него полностью **избавится либо отключить.  
Команда на отключение Bumblebee:**

`sudo systemctl disable bumblebeed`

Приступаем к установки, первым делом проверяем что у вас установлены драйвера для **Intel** видеокарты, либо устанавливаем их

`sudo pacman -S xf86-video-intel`

добавим в модули запись **i915** (самая первая раскомментированая **строчка MODULES=()** )

`sudo nano /etc/mkinitcpio.conf`

Установим драйвера **Nvidia**

`sudo pacman -S nvidia nvidia-utils lib32-nvidia-utils bbswitch`

Обновим RAM запись

`sudo mkinitcpio -P`

Устанавливаем сам **Optimus Manager **

`yay -S optimus-manager`

**В Manjaro доступен из офф репозитория**

`sudo pacman -S optimus-manager`

Так же утилиту для настройки графики и для переключения

`yay -S optimus-manager-qt`

Добавляем сервис в автозагрузку

`sudo systemctl enable optimus-manager`

Перезагружаемся

Используем утилиту для переключения либо команды в терминале

`optimus-manager --switch nvidia`

`optimus-manager --switch intel`

`optimus-manager --switch hybrid`

Узнает какой видеокартой пользуемся

`glxinfo | grep OpenGL`

Так же можно редактировать загрузочную запись, для принудительной загрузки с выбраной видеокарты, просто добавьте строчку в параметры ядра в конфиге grub или systemd-boot

Запуск с Intel

`optimus-manager.startup=intel`

Запуск с Nvidia

`optimus-manager.startup=nvidia`

* bumblebeed deb
bumblebeed deb

## bumblebeed

- 1. sudo apt-get remove --purge nvidia-*

- 2. sudo apt-get update && sudo apt-get upgrade

- 3. sudo apt-get install gcc make linux-headers-`uname -r`
sudo apt-get install dkms bbswitch-dkms

- 4. sudo add-apt-repository ppa:graphics-drivers/ppa

- 5. sudo apt-get --no-install-recommends install nvidia-390

- 6. sudo apt-get --no-install-recommends install bumblebee primus

- 7. sudo mv /etc/bumblebee/bumblebee.conf /etc/bumblebee/bumblebee.conf.bak
```
[bumblebeed]
VirtualDisplay=:8
KeepUnusedXServer=false
ServerGroup=bumblebee
TurnCardOffAtExit=true
NoEcoModeOverride=false
Driver=nvidia
XorgConfDir=/etc/bumblebee/xorg.conf.d

[optirun]
Bridge=primus
VGLTransport=proxy
PrimusLibraryPath=/usr/lib/x86_64-linux-gnu/primus:/usr/lib/i386-linux-gnu/primus
AllowFallbackToIGC=false

[driver-nvidia]
KernelDriver=nvidia
PMMethod=auto
LibraryPath=/usr/lib/nvidia-390:/usr/lib32/nvidia-390
XorgModulePath=/usr/lib/nvidia-390/xorg,/usr/lib/xorg/modules
XorgConfFile=/etc/bumblebee/xorg.conf.nvidia

[driver-nouveau]
KernelDriver=nouveau
PMMethod=auto
XorgConfFile=/etc/bumblebee/xorg.conf.nouveau
```
- 8. sudo systemctl restart bumblebeed.service

- 9. nano  /etc/modprobe.d/bumblebee.conf:

````
# 390
blacklist nvidia_390
blacklist nvidia_390_updates
blacklist nvidia_experimental_390
blacklist nvidia_drm
blacklist nvidia_modeset
blacklist nvidia_uvm
blacklist nvidiafb
blacklist nvidia
````
- 10. sudo apt-get install mesa-utils mesa-utils-extra

- 11. vblank_mode=0 optirun -vv glxgears

- 12. sudo reboot




* bumblebeed
 ###                           Bumblebee
                            =========
- Монтаж
Отключить и удалить Nouveau
Редактирование 2017-07-14: комбинация Intel + Nouveau является устаревшим. Это не поддерживается шмель больше. Поддержка Intel + Nouveau может быть исключена из шмеля в любое время. Шмель поддерживает Intel + Nvidia комбинацию только.

Nouveau видео драйвер вызывает много проблем на NVIDIA Optimus карт. Unbootable системы, сбои в процессе загрузки, система, которая загружается в неуправляемом черный экран с белым текстом мигающий курсор в левом верхнем углу, Cnchi и LiveDE замерзает лишь некоторые из эффектов Nouveau.

Если вы не испытываете любой из этих вопросов, вы можете смело пропустить этот раздел. В противном случае, продолжайте читать дальше.

Необходимы три шага, чтобы удалить Nouveau.

1. Отключите его во время загрузки с LiveMedia, чтобы иметь возможность начать LiveDE с Cnchi и завершить установку

2. Отключите его при первой загрузке установленной системы, чтобы иметь возможность достичь графического DE

3. Физическая Nuoveau пакет деинсталляция при первой загрузке; система будет использовать Intel GPU на последующих загрузках, пока установка Шмель

Шаги в деталях.

1. Используйте пункт меню загрузки по умолчанию LiveMedia. Изменение загрузочной линии и добавить к нему следующие параметры:

`modprobe.blacklist=nouveau`

Продолжить загрузку в обычном режиме.

2. Отключить Nouveau при первой загрузке установленной системы, точно так же, как и в предыдущем шаге.

3. После того, как вы достигли графический DE, откройте терминал и выполните следующую команду, чтобы полностью удалить Nou

`sudo pacman -Rc xf86-video-nouveau`

Установите Antergos без драйверов Nvidia
Выполнение новой установки Antergos, убедитесь, чтобы не устанавливать проприетарные драйверы Nvidia. Опция устанавливает драйверы для одночиповых, негибридных видеокарт, только с GPU от NVIDIA. Он не устанавливает драйверы для двойного GPU, гибридные видеокарты с NVIDIA и Intel GPU.

Оставьте драйвера (запатентованном) переключатель графического инсталлятора в положении по умолчанию OFF. Просто не трогать:

- Установить Bumblebee
На современном оборудовании, с текущими драйверами:

`sudo pacman -S bumblebee mesa xf86-video-intel nvidia lib32-nvidia-utils lib32-virtualgl nvidia-settings bbswitch`

На старом оборудовании, с 390xx устаревших драйверов:

`sudo pacman -S bumblebee mesa xf86-video-intel nvidia-390xx nvidia-390xx-utils lib32-nvidia-390xx-utils lib32-virtualgl bbswitch`

На еще более старом оборудовании, с 340xx устаревших драйверов:

`sudo pacman -S bumblebee mesa xf86-video-intel nvidia-340xx nvidia-340xx-utils lib32-nvidia-340xx-utils lib32-virtualgl bbswitch`

Добавить себя в шмель группу
Любой пользователь, который предполагается использовать Шмель должен быть добавлен к этой группе. Кроме того, пользователь должен быть членом группы видео - это, как правило, так что по умолчанию, но не всегда.

	`sudo gpasswd -a $USER bumblebee`
	`sudo gpasswd -a $USER video`

Установить патч экономии энергии
Только в случае необходимости. Пластырь подробно описан ниже.

Пакет находится по адресу:
https://web.archive.org/web/20190708164454/https://forum.antergos.com/uploads/files/1456775675942-bumblebee-3.2.1-11-x86_64.pkg.tar.xz

`sudo pacman -U /path/to/package/bumblebee-3.2.1-11-x86_64.pkg.tar.xz`

При установке пакета, pacman будет выдавать предупреждение при последующих обновлениях. Это может быть проигнорировано:

> предупреждение: шмель: локальный (3.2.1-11) новее сообщества (3.2.1-10)

- Перезагрузка системы

Включить Optimus, второго типа только BIOS
Владельцы 1-го типа BIOS могут смело пропустить этот раздел.

- Отсутствует питание
Редактировать 2016,07: Где-то в 2016.06 проблема была решена выше. Если вы установите после этой даты, скорее всего, проблема не будет присутствовать. Проверьте это с тестом, описанным здесь. Там нет необходимости устанавливать патч.

Большая часть времени NVIDIA Optimus карта работает на Intel GPU. Это сделано для экономии энергии. Nvidia GPU используется только тогда, когда явно указание сделать это - путем размещения optirun команды перед названием программы. Когда optirun выходит он должен немедленно перейти от Nvidia GPU и отключить обратно Intel GPU. Это не происходит в последнее время. Nvidia не выключается. Система продолжает работать на Nvidia.

Там нет экономии энергии, компьютер перегревается, вентиляторы охлаждения постоянно вращается на максимальной скорости. С технической точки зрения, проблема вызвана тем, что nvidia_drm, nvidia_modeset и NVIDIA модули не выгружается на optirun прекращения.

Когда система работает на Intel GPU, три модуля не используется и не загружается. Все грузятся только тогда, когда optirun начинает работать. И должен быть выгружен на optirun прекращения. Который не бывает.

Проверьте, если ваша система сталкивается с этой проблемой. После запуска открыть терминал и запустить три команды, один за другим:

`optirun --status
  Bumblebee status: Ready (3.2.1). X inactive. Discrete video card is off.`
`optirun pwd
  /home/just`
`optirun --status
  Bumblebee status: Ready (3.2.1). X inactive. Discrete video card is off.`

  Если после последней команды (третья) дискретная видеокарта выключена, как в приведенном выше примере, то система не зависят от вопроса. Вы можете пропустить этот раздел.

Если после того, как последний (третий) команда дискретное видео карта включена, то система сталкивается с этой проблемой. Вы можете решить, либо вручную, либо автоматически. Ниже описано, как это сделать.

Выключение Nvidia вручную Во-первых, давайте попробуем останова Nvidia вручную. Для того, чтобы быть уверенным, что мы столкнулись с проблемой, описанной здесь; три модуль должен быть указан точно в том же порядке, как в этом примере:

`sudo rmmod nvidia_drm nvidia_modeset nvidia`
`sudo tee <<<OFF /proc/acpi/bbswitch`

Первая команда заставляет три модуля для выгрузки. Второй один переключается Nvidia GPU выключен. Проверьте состояние Nvidia снова:

`optirun --status
  Bumblebee status: Ready (3.2.1). X inactive. Discrete video card is off.`

Давайте рассмотрим несколько сложнее испытание. Это переключит Nvidia, и затем отступить, в одной команде:

`optirun pwd && sleep 1 && sudo rmmod nvidia_drm nvidia_modeset nvidia && sudo tee <<<OFF /proc/acpi/bbswitch`

Этот метод может быть использован для переключения Nvidia выключения вручную.

Выключение Nvidia автоматически метод решения вопроса автоматически обсуждался в Arch Linux багтрекер здесь. Это применяет те же две команды видели в предыдущем разделе. Преимущество метода состоит в том, что нет необходимости вводить любую команду вручную в терминале, с повышенными привилегиями. Optirun получается нормально работать, как обычно, автоматическое переключение Nvidia и выключается, когда он начинает и завершает работу. Недостатком является то, что вам нужно установить «домашний» пакет, неизвестную к регулярным операциям РЕПО Arch. Пластырь для фиксации недостающую экономии энергии можно найти по адресу:

https://web.archive.org/web/20190708164454/https://forum.antergos.com/uploads/files/1461405434452-bumblebee-3.2.1-11-x86_64.pkg.tar.xz

  Загрузить файл и установить его в обычном режиме с Pacman, как и любой другой пакет:
`sudo pacman -U /path/to/package/bumblebee-3.2.1-11-x86_64.pkg.tar.xz`
Пакет не имеет зависимостей. Во время установки будет выдавать три информационные сообщения. Они могут быть проигнорированы. При установке пакета, pacman и pamac будут выдавать предупреждение о модернизации последующих систем. Это может быть проигнорировано, а также: предупреждение: шмель: локальный (3.2.1-11) новее, чем сообщества (3.2.1-10) Важны. После того, как пакет установлен, компьютер должен быть перезагружен. Простой выход из системы, Логин не достаточно.

-* Tочная настройка NVIDIA Optimus 
Настройки можно точно настроить параметры NVIDIA settings, запустив утилиту nvidia-settings на NVIDIA GPU

`optirun -b none nvidia-settings -c :8`
Команда является единственно правильным способом выполнить NVidia-настройки на компьютерах Optimus.

https://web.archive.org/web/20190708164454/https://antergos.com/wiki/wp-content/uploads/sites/2/2015/08/nvidia-x-server-settings-300x277.png

Любая попытка запустить утилиту NVIDIA-настройки с помощью другого синтаксиса потерпит неудачу.



* Динамическая графика с шмелями
 Динамическая графика с шмелями
=========================================
Проприетарный графический драйвер NVIDIA также может использоваться для переключения динамической графики между встроенными и дискретными поставщиками графики с использованием Bumblebee. Этот метод использует преимущества энергосберегающих функций Optimus, но может быть более сложным для успешного включения выгруженных 3D-приложений.

- Проверка драйверов
Вы можете проверить, поддерживают ли установленные драйверы 3D-графики OpenGL, выполнив следующую команду:
`$ glxinfo | grep OpenGL`

- Гибридные графические процессоры
Если у вас гибридный GPU и установлен драйвер шмели, вы можете проверить его для Intel:
`$ glxinfo | grep OpenGL`

И для NVIDIA:
`$ optirun glxinfo | grep OpenGL`

Также очень рекомендуется проверить отображение 3D-графики OpenGL, запустив программу `glxgears`.

`apt install nvidia-driver linux-headers-amd64 bumblebee-nvidia primus`

##################################################################################################################

### Настройте NVIDIA Optimus в Debian, Kali Linux со шмелями
Обновлено - 17 июля 2018 г.по Арнаб Satapathi

NVIDIA Optimus, печально известная переключаемая адаптация графики для ноутбуков / ноутбуков от NVIDIA, по-прежнему не подходит для Linux.

Вот почему большинство пользователей Linux, имеющих ноутбук с GPU Optimus, сталкиваются с такими проблемами, как горячий GPU (около 65 ° C), уменьшенный срок службы батареи, ревущий кулер и т. Д. И т. Д.nvidia optimus debianПоэтому, если вы один из тех счастливчиков с ноутбуком optimus и хотите использовать свой дискретный графический процессор, а не полностью отключать его, этот учебник для вас. Это руководство предназначено специально для Debian и других дистрибутивов, основанных на Debian, таких как Kali Linux , LMDE и т. Д.



Здесь мы собираемся сделать это с шмель , bbswitch и несвободных DEBiAN драйверов NVIDIA Optimus .

Для новичков, если вы не знаете, что это такое, вы можете взглянуть на проект шмеля . Bbswitch - это модуль ядра, используемый для отключения, и на дискретном графическом процессоре nvidia, а несвободные  драйверы nvidia optimus linux являются проприетарными драйверами графического процессора, предоставляемыми nvidia.

Преимущество шмеля над другими решениями, такими как nvidia prime, заключается в том, что вы можете запускать одно или несколько конкретных приложений с использованием дискретного графического процессора nvidia без перезапуска текущего X-сеанса на лету.


Анализ системы
Первый шаг - знать систему тщательно, сначала проверьте карту nvidia.
```
lspci -v | egrep -i 'vga | 3d | nvidia' | grep -i 'nvidia'
```
Это должно вернуть что-то вроде ниже, что даст вам краткую информацию о вашем графическом процессоре nvidia, некоторые последние графические процессоры показывают их как трехмерные контроллеры.

01: 00.0 VGA-совместимый контроллер: NVIDIA Corporation GF108M [GeForce GT 540M] (rev ff) (prog-if ff)

Теперь проверьте в настоящее время загружены нуво (бесплатно драйвер Nvidia) модуль и vga_switcheroo модуль,
```
lsmod | grep -i 'nouveau'
lsmod | grep -i 'vga_switcheroo'
```
В настоящее время Debian загружает их автоматически, если найден какой-либо дискретный графический процессор.

Выгрузите модули nouveau и установите bbswitch
Если ваше ядро ​​загружено нуворишем и другими связанными с ним модулями, его время выгружает их с помощью modprobe команды .
```
sudo modprobe -r nouveau
sudo modprobe -r vga_switcheroo
```
Позволяет установить bbswitch и связанные компоненты для его компиляции. Установка bbswitch с dkms автоматически скомпилирует правильный модуль ядра после любого будущего обновления ядра.

На этом этапе вы должны включить основной , Contrib и несвободный репозиторий, чтобы сделать это, поместите строку ниже в  файле /etc/apt/sources.list

deb http://ftp.debian.org/debian/ stretch main contrib non-free

Измените растяжку слова в соответствии с вашим disto, например, если вы используете стабильную jessie Debian, замените ее на jessie . Если вы не знаете, о чем я говорю, посмотрите там и проверьте часть sources.list .

Обновление sudo apt-get
```
sudo apt-get install gcc make linux-headers-amd64
sudo apt-get install dkms bbswitch-dkms
```
Это займет некоторое время, чтобы загрузить и установить пакеты и скомпилировать модули ядра . когда установка завершена, загрузите модуль bbswitch.

`sudo modprobe bbswitch load_state = 0`
Тестирование: теперь проверьте, работает ли bbswitch правильно или нет.

`cat / proc / acpi / bbswitch`
Это должно вернуть строку со словом OFF вместе с идентификатором шины PCI графическим процессором nvidia, идентификатор шины PCI может меняться машиной.

Еще один способ проверить это: запустите команду `lspci -v | grep  -i 'vga' | grep -i 'nvidia'`(упомянутый выше, обратите внимание на причудливые кавычки) и проверьте конец строки результата, если значение prog-if равно ff,   тогда GPU выключен, если значение равно 00, тогда GPU на.

Черный список модуля нувори
Чтобы избежать автоматической загрузки нувори и связанных модулей после каждой перезагрузки, они должны быть занесены в черный список. Просто создайте файл с вашим любимым текстовым редактором с именем `nouveau-blacklist.conf` под этой `/etc/modprobe.d/`папкой и поместите эту черную строку в него. Это также можно сделать с помощью одной строки.
```
su -c 'echo "blacklist nouveau" >> /etc/modprobe.d/nouveau-blacklist.conf'
```
Просто введите пароль root, и все готово.

Модуль bbswitch загружается автоматически при каждом включении и отключает дискретный графический процессор nvidia optimus, без необходимости его вручную загружать.

Установите nvidia несвободные драйверы и шмель
Теперь нам нужно установить несвободные драйверы nvidia, шмель и некоторые связанные дополнительные пакеты.
```
sudo apt-get install nvidia-kernel-dkms nvidia-xconfig nvidia-settings
sudo apt-get install nvidia-vdpau-driver vdpau-va-driver mesa-utils
```
Это установит несвободные драйверы nvidia, драйвер ядра nvidia, специфическую OpenGL-библиотеку nvidia и т. Д. И другие зависимости. Теперь установите шмелю,
```
sudo apt-get install bumblebee-nvidia
```
Подождите некоторое время, чтобы завершить процесс установки.

- Установка VirtualGL
VirtualGL требуется для команды optirun в качестве моста, но, к сожалению, в репозитории Debian нет пакета VirtualGL, поэтому нам нужно его загрузить. Перейдите в репозиторий sourceforge VirtualGL и загрузите соответствующий пакет для своей системы. т.е. если вы используете 64-разрядный Debian, загрузите последний пакет amd64. Теперь установите его с помощью dpkg.
```
sudo dpkg -i ~ / Загрузки / virtualgl_2.4.1_amd64.deb
```
Также не забудьте изменить путь в соответствии с тем, где вы загружаете файл.

Настройте nvidia optimus со шмелем
К счастью, шмель отлично работает с настройкой по умолчанию. Но если вы хотите внести какие-либо изменения в настройки, отредактируйте /etc/bumblebee/bumblebee.conf файл как root с помощью вашего любимого текстового редактора и перезапустите службу шмеля с помощью этой команды sudo service bumblebeed restart.

Доступ к дискретному графическому процессору nvidia требует привилегий root, поэтому вам нужно добавить имя пользователя вашей системы в группу шмелей.
```
sudo usermod -aG bumblebee $ USER
```
Теперь перезапустите демона шмеля sudo service bumblebeed restart. Теперь вы закончили, перезагрузите систему.

Необязательно: вам может потребоваться добавить дополнительную конфигурацию в xorg.conf.nvidia файл, чтобы избежать ошибки, связанной с модулем мыши.

Откройте  `/etc/bumblebee/xorg.conf.nvidia`файл с любимым текстовым редактором с  правами root  , а затем добавьте дополнительную конфигурацию.
```
Section "Screen"
    Identifier "Default Screen"
    Device "DiscreteNvidia"
EndSection
```
Сохраните файл и выйдите из текстового редактора и перезапустите демона bumblebee.

Тестирование возможности переключения графики
После перезагрузки системы вы готовы протестировать программу glxgears .
```
optirun -vv glxgears
```
Должна быть какая-то задержка (около 3-4 секунд) перед запуском glxgears, если она вернется примерно на 1000 FPS, это означает, что оптимизатор NVIDIA работает правильно.

Этот шаг почти идентичен проверке драйвера nvidia на ubuntu .

Для получения дополнительной информации о команде optirun см. Справочную страницу man optirun  , и запустите optirun с различными аргументами, например
```
optirun -v -b virtualgl -c jpeg glxgears
```
Более подробное тестирование и бенчмаркинг графического процессора NVIDIA можно было бы сделать с помощью furmark , который возвращает более точный результат, чем этот простой тест glxgears.

- Поиск проблемы
Я не сталкивался с какой-либо проблемой во время установки и тестирования с драйвером Debian stretch, kernel 4.1.0-amd64, nvidia-340.67.

Просто не забудьте добавить apt несвободный репозиторий, установить VirtualGL и добавить свое имя пользователя в группу шмелей.

Иногда вам может потребоваться добавить несколько разных параметров GRUB, чтобы заблокировать автоматическую загрузку драйвера nouveau. Подробнее о ссылке ниже.

ОБНОВЛЕНИЕ: поскольку некоторые читатели сталкиваются с проблемами с debian nvidia optimus  , I'hv написал еще один учебник специально для устранения неполадок, основанный на обратной связи с читателем. Надеюсь, это будет полезно, вот урок> Устранение неполадок NVIDIA Optimus в Debain .

Лучшая практика. Если BIOS вашего ноутбука или UEFI позволяют полностью отключить дискретный графический процессор nvidia, отключите его перед установкой ОС и снова включите его после завершения установки. Делая это, вы можете избежать некоторых проблем, вызванных модулем ядра vga_switcheroo . (Я сделал это много времени 🙂)


