* Шрифты
Во-первых, я всегда начинаю настройку с шрифтов убунту: пробовал разные, но ничего лучше для интерфейса не нашел.

Добавляет сами шрифты и, вроде бы, настройки fontconfig как в убунте:

https://copr.fedorainfracloud.org/coprs/chenxiaolong/ubuntu-fonts/

Во-вторых, не пытайся сделать из него классические ДЕ с миллиардом расширений. Они будут периодически ломаться, а у тебя будет подгорать.

* Рабочие столы.
Лучше избегать множества рабочих столов. Я решил пойти по другому пути и таки попробовать понять, чем же меня пытаются накормить разработчики гнома. На это решение меня подвиг стрим одного из разработчиков, который, как оказалось, использует дефолтный гном. Если его устраивает, может и меня тоже устроит, – подумал я и переключился на динамические рабочие столы, вместо 5-6 статических.

Смысл в том, что почти все запускаешь на первом рабочем столе. На первый взгляд кажется, что будет гора мусора, в которой невозможно разобраться. Но переключаешься ты ведь все равно через Super+Tab, который автоматически предлагает тебе два-три последних приложения. Да, на этом воркспейсе находятся и другие приложения, всякие телеграммы, торент клиенты, браузеры, плееры и прочее, но ведь большинство приложений используется в maximize-режиме и остальное просто не видно. Тогда зачем постоянно держать десяток полупустых рабочих столов, постоянно думать где у тебя что и на какой стол закинуть новое приложение? Часто оказывается, что для задачи нужно приложение, которое открыто на другом столе и его надо перемещать..

Но, от рабочих столов я не призываю отказываться, я лишь советую использовать их по уму: только тогда, когда у тебя есть долговременная и строгая задача. Тогда можно открыть новый рабочий стол и разместить все необходимое на нем. Переключение между рабочими столами Super-PgUp/PgDown – если у нас их немного, то это сочетание вполне работает, цифры не нужны. Поскольку столы динамические, они создаются автоматически по мере надобности, когда ты переключаешься на последний – Super-End.

По возможности все приложения открываем в Maximize – Super-ArrowUp.

* Док
Док не нужен. Занимает место, периодически ломается, из-за большого кол-ва избранных приложений только вводит в ступор, постоянно из дюжины иконок пытаешься найти нужную, понять на каком рабочем столе оно запущено, и запущно ли вообще. Встроенного дока по клавише Super для избранного вполне хватает.

* Трей.
В трее мы привыкли видеть такие приложения как плеер, торрент, им-клиенты и т.п. Трей и нужен, и ненужен. Для обычных приложений, вроде плеера, телеги, торрента, стима – не нужен, сразу в настройках приложений отключаем сворачивание в трей. Запускаем их на первом рабочем столе, они болтаются в конце списка Super-Tab и не мешают. И, в отличие от трея, на них можно легко переключиться без мышки. Для чего трей нужен? Дробокс, мега и т.п. – к сожалению авторы игнорируют маняфантазии гноморазработчиков и лепят говнотрей. Для них ставим расширение gnome-shell-extension-appindicator из репов. Работает криво, но как-то работает.

* Переключение приложений
Super-Tab для переключения между приложениями, Super-<клавиша выше Tab> – переключение между окнами одного приложения. Есть еще расширение Switcher – весьма удобное, но я пользоваться не стал, т.к. стараюсь уменьшить кол-во расширений. Недавно открыл для себя один хоткей: Если включить переключалку Super-Tab и на отпуская Super нажать q на выделенном приложении, оно закроется.

* Переключение языков
Super-Space – не надо ничего выдумывать, это сейчас дефолт в любой оси.

* Терминал
Запуск по Super+Enter (нужно настраивать самому) – стандартный хоткей в тайлинг-вм. Лучше не плодить миллион окон терминала без необходимости, а использовать вкладки (в gnome-terminal они сделаны удобно) или tmux. Новая вкладка Ctrl-Shift-t, закрыть вкладку Ctrl-Shift-w, переключение Ctrl-PgUp/PgDown (или Alt-1/2/3/4 etc.).

* Мониторинг системы
conky. Чтобы увидеть рабочий стол с конки, настраиваем хоткей Super-d Hide all normal windows.

* Настройка переменных окружения
PATH можно настроить только в ~/.profile, в вейланд-сессии другие пути у меня не работали. Даже через юзерский systemd.
е
