**Почта Попробовав gnus, который я нашел слишком старым и не очень, на
мой взгляд, не имеет таких функций, как возможность удалять некоторые
электронные письма и иметь возможность легко писать электронные письма с
помощью org, я наконец нашел свое счастье с mu4e.

Я использую mbsync, чтобы иметь возможность синхронизировать почту на
сервере IMAP с локальной папкой Maildir. Я привык использовать
offlineimap, но мне он показался медленнее, чем mbsync, поэтому я
отделился от него.

#+BEGIN_QUOTE
  ПРИМЕЧАНИЕ: чтобы использовать mbsync с учетной записью Gmail, вам
  необходимо включить доступ для менее безопасных приложений в вашей
  учетной записи Google.
#+END_QUOTE

* mu4e
  :PROPERTIES:
  :CUSTOM_ID: mu4e
  :END:

Прежде чем вы сможете использовать эту конфигурацию, убедитесь, что вы
установили mu в своей операционной системе и создали каталоги,
соответствующие каталогам в вашем почтовом ящике.

Затем инициализируйте базу данных mu, заменив значения --maildir и
--my-address вашими:

=mu init --maildir ~/Maildir --my-address=${EMAIL}=

Теперь осталось настроить mu4e:

#+BEGIN_EXAMPLE
   add-to-list 'load-path "/usr/share/emacs/site-lisp/mu4e")

  (use-package mu4e
    :ensure nil
    :ensure-system-package mu
    :custom
    (mu4e-attachment-dir "~/Downloads")
    (mu4e-change-filenames-when-moving t)
    (mu4e-confirm-quit nil)
    (mu4e-compose-dont-reply-to-self t)
    (mu4e-compose-signature-auto-include nil)
    (mu4e-drafts-folder "/gmail/Drafts")
    (mu4e-get-mail-command (format "mbsync -c '%s/isync/mbsyncrc' -a" xdg-config))
    (mu4e-html2text-command "iconv -c -t utf-8 | pandoc -f html -t plain")
    (mu4e-maildir "~/Maildir/gmail")
    (mu4e-maildir-shortcuts
     '(("/gmail/All Mail" . ?a)
       ("/gmail/Inbox" . ?i)
       ("/gmail/Drafts" . ?D)
       ("/gmail/Sent" . ?s)
       ("/gmail/Starred" . ?S)
       ("/gmail/Trash" . ?T)))
    (mu4e-org-contacts-file "~/.personal/agenda/contacts.org")
    (mu4e-refile-folder "/gmail/Archive")
    (mu4e-sent-folder "/gmail/Sent")
    (mu4e-trash-folder "/gmail/Trash")
    (mu4e-update-interval 60)
    (mu4e-use-fancy-chars t)
    (mu4e-view-show-addresses t)
    (mu4e-view-show-images t)
    :config
    (add-to-list 'mu4e-headers-actions '("org-contact-add" . mu4e-action-add-org-contact) t)
    (add-to-list 'mu4e-view-actions '("org-contact-add" . mu4e-action-add-org-contact) t))
#+END_EXAMPLE

Возможность читать почту - это хорошо, но получать уведомления, когда мы
получаем почту, лучше! Следующие несколько строк позволяют получать
уведомления на рабочем столе и отображать строку режима для mu4e:

#+BEGIN_EXAMPLE
    (use-package mu4e-alert
    :after mu4e
    :hook ((after-init . mu4e-alert-enable-mode-line-display)
           (after-init . mu4e-alert-enable-notifications))
    :config (mu4e-alert-set-default-style 'libnotify))
#+END_EXAMPLE

* Sending Mail
  :PROPERTIES:
  :CUSTOM_ID: sending-mail
  :END:

Прежде чем отправлять сообщения электронной почты, создайте файл
.authinfo, если это еще не сделано. Затем добавьте следующие две строки,
заменив terencio.agozzino (который соответствует моему адресу gmail
terencio.agozzino@gmail.com без имени домена) и на те, которые
соответствуют вашей реальной информации:

#+BEGIN_EXAMPLE
     machine imap.gmail.com login terencio.agozzino password <password> port 993
     machine smtp.gmail.com login terencio.agozzino password <password> port 587
#+END_EXAMPLE

Подобно IRC, если вы хотите сохранить свой пароль в файле GPG, вам
просто нужно указать список приоритетов файлов с auth-sources, чтобы
сообщить GNU Emacs, где в первую очередь искать ваш пароль.

Затем зашифруйте этот файл с помощью gpg -c .authinfo и не забудьте
удалить файл .authinfo.

#+BEGIN_EXAMPLE
   (use-package message
    :ensure nil
    :custom (send-mail-function 'smtpmail-send-it))

  (use-package smtpmail
    :ensure nil
    :custom
    (smtpmail-smtp-server "smtp.gmail.com")
    (smtpmail-smtp-service 587)
    (smtpmail-smtp-user "terencio.agozzino")
    (smtpmail-stream-type 'starttls))
#+END_EXAMPLE

Все, что вам сейчас нужно, это протестировать отправку писем с помощью
C-x m или напрямую из mu4e!
